CREATE TABLE STOCKSS
(
STORE_ID NUMBER(10),
PRODUCT_ID NUMBER(10),
QUANTITY NUMBER(5),
PRIMARY KEY (STORE_ID, PRODUCT_ID),
FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTSS(PRODUCT_ID)
)
/
